version: '3.5'
services:
  postgresql:
    image: postgres:12.17-bullseye
    container_name: pgs-db
    restart: "no"
    environment:
      - POSTGRES_USER=
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=
      - PGDATA=/data/db
    volumes:
      - ./pmdb:/data/db
      - ./init:/docker-entrypoint-initdb.d
  appserver:
    image: projectm-server
    container_name: projectm-server
    restart: "always"
    environment:
      - DB_HOST=postgresql
      - DB_PORT=5432
    ports:
      - 3001:3001